### ISSUE TITLE
[Q] Is there any way to convert existing Sixel, Kitty and Iterm images to FBTERM graphics?

### ISSUE THREAD

**Issue by xplshn** [BourgeoisBear/rasterm#1]
This question may be offtopic, but... Is there any way to decode images from Sixel to fb graphics? Maybe convert Sixel to PPM to then open with fbsplash? Thanks!

**Comment by BourgeoisBear** [comment]
rasterm sixel is encode-only.  saitoha has *the* library for encoding & decoding sixel:

https://github.com/saitoha/libsixel

i think it's in C.

kitty & iterm are just base64s of the original image.  kitty accepts PNG, RGB(24), & RGBA(32).  iterm does "*any image format that macOS supports*" (png, gif, jpg, pdf, etc).
