### ISSUE TITLE
Borrow framebuffer support from `eimg`?

### ISSUE THREAD

**Issue by xplshn** [BourgeoisBear/rasterm#3]
Hi! I am using your library in my program, my program is a simple image to terminal encoding program, it supports displaying to the framebuffer, I was wondering if maybe that could be added in this library instead. Would you be interested in adding framebuffer support? https://github.com/xplshn/eimg

Thanks for the awesome library BTW! Its been fantastic!

**Comment by BourgeoisBear** [comment]
I'm glad you've gotten some use out of it, but rasterm is a cross-platform image encoder for terminal emulators, while framebuffer is linux-only, and entirely orthogonal to terminal emulation, so I find this request confusing.

**Comment by xplshn** [comment]
Oh, right... I forgot that the framebuffer implementation would be Linux/Illumos-only.
